version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
